// Generated by scripts/build-tokens.mjs from tokens/*.json. Do not edit by hand.

export type TokenMeta = {
  name: string;
  type: string;
  value: unknown;
  ref: string | null;
  description: string | null;
  layer: 'primitive' | 'semantic' | 'component';
};

export const tokenMeta: TokenMeta[] = [
  {
    "name": "color.ink.100",
    "type": "color",
    "value": "#F8F7F1",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.ink.200",
    "type": "color",
    "value": "#F2F0EA",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.ink.300",
    "type": "color",
    "value": "#E3E1DB",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.ink.400",
    "type": "color",
    "value": "#C5C4BE",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.ink.500",
    "type": "color",
    "value": "#94928D",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.ink.600",
    "type": "color",
    "value": "#6D6C67",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.ink.700",
    "type": "color",
    "value": "#4E4D48",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.ink.800",
    "type": "color",
    "value": "#2C2B27",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.ink.900",
    "type": "color",
    "value": "#141411",
    "ref": null,
    "description": "Neutrals: text, surfaces and borders.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.100",
    "type": "color",
    "value": "#F5F6FF",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.200",
    "type": "color",
    "value": "#E0E3FE",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.300",
    "type": "color",
    "value": "#C2C8FF",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.400",
    "type": "color",
    "value": "#9BA1FD",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.500",
    "type": "color",
    "value": "#6C63FF",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.600",
    "type": "color",
    "value": "#5347D3",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.700",
    "type": "color",
    "value": "#4034AC",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.800",
    "type": "color",
    "value": "#2E2383",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.purple.900",
    "type": "color",
    "value": "#1B1355",
    "ref": null,
    "description": "Brand, primary action and the Credit vertical.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.100",
    "type": "color",
    "value": "#E9FCF5",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.200",
    "type": "color",
    "value": "#D1F5E7",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.300",
    "type": "color",
    "value": "#ABEBD4",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.400",
    "type": "color",
    "value": "#7BDABB",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.500",
    "type": "color",
    "value": "#46BE9C",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.600",
    "type": "color",
    "value": "#0F7B61",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.700",
    "type": "color",
    "value": "#0A614C",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.800",
    "type": "color",
    "value": "#034938",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.mint.900",
    "type": "color",
    "value": "#002F23",
    "ref": null,
    "description": "Save vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.100",
    "type": "color",
    "value": "#F2F7FF",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.200",
    "type": "color",
    "value": "#DEEDFF",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.300",
    "type": "color",
    "value": "#C4DDFE",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.400",
    "type": "color",
    "value": "#9CC7FF",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.500",
    "type": "color",
    "value": "#6AA8F7",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.600",
    "type": "color",
    "value": "#2D64A7",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.700",
    "type": "color",
    "value": "#1E4D87",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.800",
    "type": "color",
    "value": "#123865",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.sky.900",
    "type": "color",
    "value": "#082240",
    "ref": null,
    "description": "Invest vertical accent.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.100",
    "type": "color",
    "value": "#FFF4F2",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.200",
    "type": "color",
    "value": "#FFE7E2",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.300",
    "type": "color",
    "value": "#FED4CC",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.400",
    "type": "color",
    "value": "#FEB8AB",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.500",
    "type": "color",
    "value": "#FF8D7A",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.600",
    "type": "color",
    "value": "#B45243",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.700",
    "type": "color",
    "value": "#913D30",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.800",
    "type": "color",
    "value": "#6C2B21",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.coral.900",
    "type": "color",
    "value": "#461912",
    "ref": null,
    "description": "Warm Coral from the brand brief. Not mapped to any semantic token.",
    "layer": "primitive"
  },
  {
    "name": "color.lime.100",
    "type": "color",
    "value": "#F4FCD7",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.lime.200",
    "type": "color",
    "value": "#EFFCBA",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.lime.300",
    "type": "color",
    "value": "#E8FC90",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.lime.400",
    "type": "color",
    "value": "#E1F964",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.lime.500",
    "type": "color",
    "value": "#D9F23F",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.lime.600",
    "type": "color",
    "value": "#8C9D03",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.lime.700",
    "type": "color",
    "value": "#64710C",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.lime.800",
    "type": "color",
    "value": "#444E02",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.lime.900",
    "type": "color",
    "value": "#2B3200",
    "ref": null,
    "description": "Highlight: the 10% (milestone moments only).",
    "layer": "primitive"
  },
  {
    "name": "color.green.100",
    "type": "color",
    "value": "#E9FDEE",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.green.200",
    "type": "color",
    "value": "#CCF2D6",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.green.300",
    "type": "color",
    "value": "#A0E3B4",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.green.400",
    "type": "color",
    "value": "#67CA8A",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.green.500",
    "type": "color",
    "value": "#17A35B",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.green.600",
    "type": "color",
    "value": "#107641",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.green.700",
    "type": "color",
    "value": "#085D31",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.green.800",
    "type": "color",
    "value": "#014422",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.green.900",
    "type": "color",
    "value": "#012A13",
    "ref": null,
    "description": "Success status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.100",
    "type": "color",
    "value": "#FFF4F2",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.200",
    "type": "color",
    "value": "#FFDCD6",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.300",
    "type": "color",
    "value": "#FEB8AE",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.400",
    "type": "color",
    "value": "#FC8172",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.500",
    "type": "color",
    "value": "#E0352B",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.600",
    "type": "color",
    "value": "#B81814",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.700",
    "type": "color",
    "value": "#940204",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.800",
    "type": "color",
    "value": "#6D0505",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.red.900",
    "type": "color",
    "value": "#480000",
    "ref": null,
    "description": "Error status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.100",
    "type": "color",
    "value": "#FFF5E9",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.200",
    "type": "color",
    "value": "#FEEAD0",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.300",
    "type": "color",
    "value": "#FED9AA",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.400",
    "type": "color",
    "value": "#FDC16E",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.500",
    "type": "color",
    "value": "#F0A21A",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.600",
    "type": "color",
    "value": "#B57801",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.700",
    "type": "color",
    "value": "#8D5E0E",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.800",
    "type": "color",
    "value": "#694403",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.amber.900",
    "type": "color",
    "value": "#472C00",
    "ref": null,
    "description": "Warning status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.100",
    "type": "color",
    "value": "#F1F7FF",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.200",
    "type": "color",
    "value": "#D5E7FE",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.300",
    "type": "color",
    "value": "#ADD0FD",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.400",
    "type": "color",
    "value": "#6EAEFF",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.500",
    "type": "color",
    "value": "#2B7FE0",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.600",
    "type": "color",
    "value": "#1162B8",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.700",
    "type": "color",
    "value": "#014B95",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.800",
    "type": "color",
    "value": "#03376E",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.azure.900",
    "type": "color",
    "value": "#002148",
    "ref": null,
    "description": "Info status.",
    "layer": "primitive"
  },
  {
    "name": "color.surface.page",
    "type": "color",
    "value": "#F2F0EA",
    "ref": "color.ink.200",
    "description": "Screen background.",
    "layer": "semantic"
  },
  {
    "name": "color.surface.card",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.ink.100",
    "description": "Cards, fields and the tab bar.",
    "layer": "semantic"
  },
  {
    "name": "color.surface.inverse",
    "type": "color",
    "value": "#141411",
    "ref": "color.ink.900",
    "description": "Dark surface: Banking and the active tab pill.",
    "layer": "semantic"
  },
  {
    "name": "color.surface.scrim",
    "type": "color",
    "value": "#141411",
    "ref": "color.ink.900",
    "description": "Scrim behind sheets and modals, with opacity.overlay.",
    "layer": "semantic"
  },
  {
    "name": "color.text.primary",
    "type": "color",
    "value": "#141411",
    "ref": "color.ink.900",
    "description": "Primary text, headlines and balances.",
    "layer": "semantic"
  },
  {
    "name": "color.text.secondary",
    "type": "color",
    "value": "#4E4D48",
    "ref": "color.ink.700",
    "description": "Supporting text and descriptions.",
    "layer": "semantic"
  },
  {
    "name": "color.text.tertiary",
    "type": "color",
    "value": "#6D6C67",
    "ref": "color.ink.600",
    "description": "Metadata, captions and inactive icons.",
    "layer": "semantic"
  },
  {
    "name": "color.text.on-inverse",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.ink.100",
    "description": "Text on surface.inverse.",
    "layer": "semantic"
  },
  {
    "name": "color.text.on-inverse-muted",
    "type": "color",
    "value": "#C5C4BE",
    "ref": "color.ink.400",
    "description": "Secondary text on surface.inverse.",
    "layer": "semantic"
  },
  {
    "name": "color.brand.primary.pressed",
    "type": "color",
    "value": "#4034AC",
    "ref": "color.purple.700",
    "description": "Primary button while pressed.",
    "layer": "semantic"
  },
  {
    "name": "color.brand.primary.disabled",
    "type": "color",
    "value": "#C2C8FF",
    "ref": "color.purple.300",
    "description": "Disabled primary button (exempt from contrast).",
    "layer": "semantic"
  },
  {
    "name": "color.brand.primary",
    "type": "color",
    "value": "#5347D3",
    "ref": "color.purple.600",
    "description": "Primary action and focus. One purple button per screen.",
    "layer": "semantic"
  },
  {
    "name": "color.brand.on-primary",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.ink.100",
    "description": "Text and icons on brand.primary.",
    "layer": "semantic"
  },
  {
    "name": "color.brand.logo",
    "type": "color",
    "value": "#6C63FF",
    "ref": "color.purple.500",
    "description": "Vuno Purple from the brand brief. Logo and text-free brand surfaces only.",
    "layer": "semantic"
  },
  {
    "name": "color.border.default",
    "type": "color",
    "value": "#E3E1DB",
    "ref": "color.ink.300",
    "description": "Decorative border for cards and dividers.",
    "layer": "semantic"
  },
  {
    "name": "color.border.input",
    "type": "color",
    "value": "#6D6C67",
    "ref": "color.ink.600",
    "description": "Boundary of fields and controls (3:1).",
    "layer": "semantic"
  },
  {
    "name": "color.border.focus",
    "type": "color",
    "value": "#5347D3",
    "ref": "color.purple.600",
    "description": "Keyboard focus ring.",
    "layer": "semantic"
  },
  {
    "name": "color.status.success.bg",
    "type": "color",
    "value": "#CCF2D6",
    "ref": "color.green.200",
    "description": "Success chip background.",
    "layer": "semantic"
  },
  {
    "name": "color.status.success.fg",
    "type": "color",
    "value": "#014422",
    "ref": "color.green.800",
    "description": "Success text and icon.",
    "layer": "semantic"
  },
  {
    "name": "color.status.error.bg",
    "type": "color",
    "value": "#FFDCD6",
    "ref": "color.red.200",
    "description": "Error chip background.",
    "layer": "semantic"
  },
  {
    "name": "color.status.error.fg",
    "type": "color",
    "value": "#6D0505",
    "ref": "color.red.800",
    "description": "Error text and icon.",
    "layer": "semantic"
  },
  {
    "name": "color.status.error.border",
    "type": "color",
    "value": "#B81814",
    "ref": "color.red.600",
    "description": "Border of a field with an error.",
    "layer": "semantic"
  },
  {
    "name": "color.status.warning.bg",
    "type": "color",
    "value": "#FEEAD0",
    "ref": "color.amber.200",
    "description": "Warning chip background.",
    "layer": "semantic"
  },
  {
    "name": "color.status.warning.fg",
    "type": "color",
    "value": "#472C00",
    "ref": "color.amber.900",
    "description": "Warning text and icon.",
    "layer": "semantic"
  },
  {
    "name": "color.status.info.bg",
    "type": "color",
    "value": "#D5E7FE",
    "ref": "color.azure.200",
    "description": "Info chip background.",
    "layer": "semantic"
  },
  {
    "name": "color.status.info.fg",
    "type": "color",
    "value": "#03376E",
    "ref": "color.azure.800",
    "description": "Info text and icon.",
    "layer": "semantic"
  },
  {
    "name": "color.vertical.banking.accent",
    "type": "color",
    "value": "#141411",
    "ref": "color.ink.900",
    "description": "Banking accent.",
    "layer": "semantic"
  },
  {
    "name": "color.vertical.banking.on-accent",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.ink.100",
    "description": "Content on the Banking accent.",
    "layer": "semantic"
  },
  {
    "name": "color.vertical.save.accent",
    "type": "color",
    "value": "#ABEBD4",
    "ref": "color.mint.300",
    "description": "Save accent.",
    "layer": "semantic"
  },
  {
    "name": "color.vertical.save.on-accent",
    "type": "color",
    "value": "#002F23",
    "ref": "color.mint.900",
    "description": "Content on the Save accent.",
    "layer": "semantic"
  },
  {
    "name": "color.vertical.invest.accent",
    "type": "color",
    "value": "#C4DDFE",
    "ref": "color.sky.300",
    "description": "Invest accent.",
    "layer": "semantic"
  },
  {
    "name": "color.vertical.invest.on-accent",
    "type": "color",
    "value": "#082240",
    "ref": "color.sky.900",
    "description": "Content on the Invest accent.",
    "layer": "semantic"
  },
  {
    "name": "color.vertical.credit.accent",
    "type": "color",
    "value": "#C2C8FF",
    "ref": "color.purple.300",
    "description": "Credit accent.",
    "layer": "semantic"
  },
  {
    "name": "color.vertical.credit.on-accent",
    "type": "color",
    "value": "#1B1355",
    "ref": "color.purple.900",
    "description": "Content on the Credit accent.",
    "layer": "semantic"
  },
  {
    "name": "color.highlight.accent",
    "type": "color",
    "value": "#D9F23F",
    "ref": "color.lime.500",
    "description": "The 10% lime: milestone chip, active tab icon.",
    "layer": "semantic"
  },
  {
    "name": "color.highlight.on-accent",
    "type": "color",
    "value": "#141411",
    "ref": "color.ink.900",
    "description": "Content on the lime.",
    "layer": "semantic"
  },
  {
    "name": "space.2xs",
    "type": "dimension",
    "value": 4,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "space.xs",
    "type": "dimension",
    "value": 8,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "space.sm",
    "type": "dimension",
    "value": 12,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "space.md",
    "type": "dimension",
    "value": 16,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "space.lg",
    "type": "dimension",
    "value": 20,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "space.xl",
    "type": "dimension",
    "value": 24,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "space.2xl",
    "type": "dimension",
    "value": 32,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "space.3xl",
    "type": "dimension",
    "value": 48,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "space.inset.screen",
    "type": "dimension",
    "value": 20,
    "ref": "space.lg",
    "description": "Screen side margin.",
    "layer": "semantic"
  },
  {
    "name": "space.inset.card",
    "type": "dimension",
    "value": 20,
    "ref": "space.lg",
    "description": "Card padding.",
    "layer": "semantic"
  },
  {
    "name": "space.inset.chip",
    "type": "dimension",
    "value": 8,
    "ref": "space.xs",
    "description": "Chip horizontal padding (vertical: space.2xs).",
    "layer": "semantic"
  },
  {
    "name": "space.gap.list",
    "type": "dimension",
    "value": 8,
    "ref": "space.xs",
    "description": "Between list rows and cards in a grid.",
    "layer": "semantic"
  },
  {
    "name": "space.gap.stack",
    "type": "dimension",
    "value": 16,
    "ref": "space.md",
    "description": "Between blocks inside a section.",
    "layer": "semantic"
  },
  {
    "name": "space.gap.section",
    "type": "dimension",
    "value": 32,
    "ref": "space.2xl",
    "description": "Between sections.",
    "layer": "semantic"
  },
  {
    "name": "radius.xs",
    "type": "dimension",
    "value": 4,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "radius.sm",
    "type": "dimension",
    "value": 8,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "radius.md",
    "type": "dimension",
    "value": 16,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "radius.lg",
    "type": "dimension",
    "value": 20,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "radius.xl",
    "type": "dimension",
    "value": 28,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "radius.full",
    "type": "dimension",
    "value": 999,
    "ref": null,
    "description": "Fully rounded (pill or circle).",
    "layer": "primitive"
  },
  {
    "name": "radius.input",
    "type": "dimension",
    "value": 16,
    "ref": "radius.md",
    "description": "Text fields and pickers.",
    "layer": "semantic"
  },
  {
    "name": "radius.card",
    "type": "dimension",
    "value": 20,
    "ref": "radius.lg",
    "description": "Cards.",
    "layer": "semantic"
  },
  {
    "name": "radius.sheet",
    "type": "dimension",
    "value": 28,
    "ref": "radius.xl",
    "description": "Top corners of bottom sheets.",
    "layer": "semantic"
  },
  {
    "name": "radius.pill",
    "type": "dimension",
    "value": 999,
    "ref": "radius.full",
    "description": "Buttons, chips, tab bar and icon buttons.",
    "layer": "semantic"
  },
  {
    "name": "font.family.ui",
    "type": "fontFamily",
    "value": "Plus Jakarta Sans",
    "ref": null,
    "description": "Interface sans.",
    "layer": "primitive"
  },
  {
    "name": "font.family.display",
    "type": "fontFamily",
    "value": "Bricolage Grotesque",
    "ref": null,
    "description": "Display face for headlines and balances (part of the 20%).",
    "layer": "primitive"
  },
  {
    "name": "font.size.xs",
    "type": "dimension",
    "value": 12,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "font.size.sm",
    "type": "dimension",
    "value": 14,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "font.size.md",
    "type": "dimension",
    "value": 16,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "font.size.lg",
    "type": "dimension",
    "value": 20,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "font.size.xl",
    "type": "dimension",
    "value": 28,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "font.size.2xl",
    "type": "dimension",
    "value": 52,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "font.role.balance",
    "type": "typography",
    "value": {
      "fontFamily": "BricolageGrotesque_700Bold",
      "fontSize": 52,
      "lineHeight": 56,
      "letterSpacing": -1.04
    },
    "ref": null,
    "description": "Main balance figure. One per screen.",
    "layer": "semantic"
  },
  {
    "name": "font.role.headline",
    "type": "typography",
    "value": {
      "fontFamily": "BricolageGrotesque_700Bold",
      "fontSize": 28,
      "lineHeight": 32,
      "letterSpacing": -0.28
    },
    "ref": null,
    "description": "Screen headline, amount on a vertical card.",
    "layer": "semantic"
  },
  {
    "name": "font.role.title",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 20,
      "lineHeight": 28,
      "letterSpacing": 0
    },
    "ref": null,
    "description": "Section, sheet and modal titles.",
    "layer": "semantic"
  },
  {
    "name": "font.role.body",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_400Regular",
      "fontSize": 16,
      "lineHeight": 24,
      "letterSpacing": 0
    },
    "ref": null,
    "description": "Running text and descriptions.",
    "layer": "semantic"
  },
  {
    "name": "font.role.label",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 14,
      "lineHeight": 20,
      "letterSpacing": 0
    },
    "ref": null,
    "description": "Buttons, labels, names and amounts in lists.",
    "layer": "semantic"
  },
  {
    "name": "font.role.caption",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_500Medium",
      "fontSize": 12,
      "lineHeight": 16,
      "letterSpacing": 0.12
    },
    "ref": null,
    "description": "Dates, metadata and chips.",
    "layer": "semantic"
  },
  {
    "name": "elevation.sm",
    "type": "shadow",
    "value": "0px 6px 20px 0px #1414111F",
    "ref": null,
    "description": "ink.900 at 12%.",
    "layer": "primitive"
  },
  {
    "name": "elevation.md",
    "type": "shadow",
    "value": "0px 12px 32px 0px #1414112E",
    "ref": null,
    "description": "ink.900 at 18%.",
    "layer": "primitive"
  },
  {
    "name": "elevation.floating",
    "type": "shadow",
    "value": "0px 6px 20px 0px #1414111F",
    "ref": "elevation.sm",
    "description": "Tab bar and floating button.",
    "layer": "semantic"
  },
  {
    "name": "elevation.overlay",
    "type": "shadow",
    "value": "0px 12px 32px 0px #1414112E",
    "ref": "elevation.md",
    "description": "Sheets, modals and menus.",
    "layer": "semantic"
  },
  {
    "name": "border.width.sm",
    "type": "dimension",
    "value": 1,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "border.width.md",
    "type": "dimension",
    "value": 2,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "border.default",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#E3E1DB",
      "style": "solid"
    },
    "ref": null,
    "description": "Neutral cards, dividers and icon buttons.",
    "layer": "semantic"
  },
  {
    "name": "border.input",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#6D6C67",
      "style": "solid"
    },
    "ref": null,
    "description": "Text fields and controls.",
    "layer": "semantic"
  },
  {
    "name": "border.focus.ring",
    "type": "border",
    "value": {
      "width": 2,
      "color": "#5347D3",
      "style": "solid"
    },
    "ref": null,
    "description": "Keyboard focus, 2 px away from the element.",
    "layer": "semantic"
  },
  {
    "name": "opacity.40",
    "type": "number",
    "value": 0.4,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "opacity.50",
    "type": "number",
    "value": 0.5,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "opacity.disabled",
    "type": "number",
    "value": 0.4,
    "ref": "opacity.40",
    "description": "Disabled elements.",
    "layer": "semantic"
  },
  {
    "name": "opacity.overlay",
    "type": "number",
    "value": 0.5,
    "ref": "opacity.50",
    "description": "Scrim behind sheets and modals.",
    "layer": "semantic"
  },
  {
    "name": "icon.size.sm",
    "type": "dimension",
    "value": 16,
    "ref": null,
    "description": "Inside chips and next to captions.",
    "layer": "primitive"
  },
  {
    "name": "icon.size.md",
    "type": "dimension",
    "value": 24,
    "ref": null,
    "description": "Default size.",
    "layer": "primitive"
  },
  {
    "name": "icon.size.lg",
    "type": "dimension",
    "value": 32,
    "ref": null,
    "description": "Empty states and milestones.",
    "layer": "primitive"
  },
  {
    "name": "motion.duration.100",
    "type": "duration",
    "value": 100,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "motion.duration.150",
    "type": "duration",
    "value": 150,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "motion.duration.250",
    "type": "duration",
    "value": 250,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "motion.duration.400",
    "type": "duration",
    "value": 400,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "motion.duration.1800",
    "type": "duration",
    "value": 1800,
    "ref": null,
    "description": null,
    "layer": "primitive"
  },
  {
    "name": "motion.duration.press",
    "type": "duration",
    "value": 100,
    "ref": "motion.duration.100",
    "description": "Response to a touch.",
    "layer": "semantic"
  },
  {
    "name": "motion.duration.state",
    "type": "duration",
    "value": 150,
    "ref": "motion.duration.150",
    "description": "Chips, state changes and fades.",
    "layer": "semantic"
  },
  {
    "name": "motion.duration.nav",
    "type": "duration",
    "value": 250,
    "ref": "motion.duration.250",
    "description": "Navigation, sheets and cards.",
    "layer": "semantic"
  },
  {
    "name": "motion.duration.celebrate",
    "type": "duration",
    "value": 400,
    "ref": "motion.duration.400",
    "description": "10% moments.",
    "layer": "semantic"
  },
  {
    "name": "motion.duration.effect",
    "type": "duration",
    "value": 1800,
    "ref": "motion.duration.1800",
    "description": "Decorative effects that never block the UI, such as particles. Outside the transition scale (press → celebrate).",
    "layer": "semantic"
  },
  {
    "name": "motion.easing.standard",
    "type": "cubicBezier",
    "value": [
      0.2,
      0,
      0,
      1
    ],
    "ref": null,
    "description": "Entrances and changes without a spring.",
    "layer": "primitive"
  },
  {
    "name": "motion.easing.exit",
    "type": "cubicBezier",
    "value": [
      0.4,
      0,
      1,
      1
    ],
    "ref": null,
    "description": "Exits.",
    "layer": "primitive"
  },
  {
    "name": "motion.spring.soft",
    "type": "spring",
    "value": {
      "mass": 1,
      "stiffness": 300,
      "damping": 22
    },
    "ref": null,
    "description": "Buttons, cards and the tab bar indicator.",
    "layer": "semantic"
  },
  {
    "name": "motion.spring.bounce",
    "type": "spring",
    "value": {
      "mass": 1,
      "stiffness": 340,
      "damping": 20
    },
    "ref": null,
    "description": "10% moments only.",
    "layer": "semantic"
  },
  {
    "name": "size.touch.min",
    "type": "dimension",
    "value": 48,
    "ref": null,
    "description": "Minimum touch target (44 pt iOS, 48 dp Android).",
    "layer": "semantic"
  },
  {
    "name": "button.primary.bg",
    "type": "color",
    "value": "#5347D3",
    "ref": "color.brand.primary",
    "description": "Primary button background. Pressed and disabled: color.brand.primary.pressed / .disabled.",
    "layer": "component"
  },
  {
    "name": "button.primary.fg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.brand.on-primary",
    "description": "Primary button text and icon.",
    "layer": "component"
  },
  {
    "name": "button.primary.radius",
    "type": "dimension",
    "value": 999,
    "ref": "radius.pill",
    "description": "Pill-shaped buttons.",
    "layer": "component"
  },
  {
    "name": "button.primary.height",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Minimum height: the touch target.",
    "layer": "component"
  },
  {
    "name": "button.primary.font",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 14,
      "lineHeight": 20,
      "letterSpacing": 0
    },
    "ref": "font.role.label",
    "description": "Button label.",
    "layer": "component"
  },
  {
    "name": "button.secondary.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Secondary button background.",
    "layer": "component"
  },
  {
    "name": "button.secondary.fg",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Secondary button text and icon.",
    "layer": "component"
  },
  {
    "name": "button.secondary.border",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#E3E1DB",
      "style": "solid"
    },
    "ref": "border.default",
    "description": "Secondary button border.",
    "layer": "component"
  },
  {
    "name": "button.tertiary.fg",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Tertiary button text and icon: no background or border, for the lowest-weight action (Cancel, Skip).",
    "layer": "component"
  },
  {
    "name": "button.circle.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Icon button background.",
    "layer": "component"
  },
  {
    "name": "button.circle.border",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#E3E1DB",
      "style": "solid"
    },
    "ref": "border.default",
    "description": "Icon button border.",
    "layer": "component"
  },
  {
    "name": "button.circle.size",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Diameter: the touch target.",
    "layer": "component"
  },
  {
    "name": "button.circle.icon",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Icon button icon.",
    "layer": "component"
  },
  {
    "name": "action.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Quick action background.",
    "layer": "component"
  },
  {
    "name": "action.border",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#E3E1DB",
      "style": "solid"
    },
    "ref": "border.default",
    "description": "Quick action border.",
    "layer": "component"
  },
  {
    "name": "action.icon",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Quick action icon.",
    "layer": "component"
  },
  {
    "name": "action.label",
    "type": "color",
    "value": "#4E4D48",
    "ref": "color.text.secondary",
    "description": "Label under the action.",
    "layer": "component"
  },
  {
    "name": "action.inset",
    "type": "dimension",
    "value": 16,
    "ref": "space.md",
    "description": "Space around the icon (24 + 2 × 16 = 56).",
    "layer": "component"
  },
  {
    "name": "chip.radius",
    "type": "dimension",
    "value": 999,
    "ref": "radius.pill",
    "description": "Pill-shaped chips.",
    "layer": "component"
  },
  {
    "name": "chip.font",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_500Medium",
      "fontSize": 12,
      "lineHeight": 16,
      "letterSpacing": 0.12
    },
    "ref": "font.role.caption",
    "description": "Chip text.",
    "layer": "component"
  },
  {
    "name": "chip.icon",
    "type": "dimension",
    "value": 16,
    "ref": "icon.size.sm",
    "description": "Chip icon.",
    "layer": "component"
  },
  {
    "name": "chip.inset",
    "type": "dimension",
    "value": 8,
    "ref": "space.inset.chip",
    "description": "Chip horizontal padding.",
    "layer": "component"
  },
  {
    "name": "chip.status.success.bg",
    "type": "color",
    "value": "#CCF2D6",
    "ref": "color.status.success.bg",
    "description": null,
    "layer": "component"
  },
  {
    "name": "chip.status.success.fg",
    "type": "color",
    "value": "#014422",
    "ref": "color.status.success.fg",
    "description": null,
    "layer": "component"
  },
  {
    "name": "chip.status.error.bg",
    "type": "color",
    "value": "#FFDCD6",
    "ref": "color.status.error.bg",
    "description": null,
    "layer": "component"
  },
  {
    "name": "chip.status.error.fg",
    "type": "color",
    "value": "#6D0505",
    "ref": "color.status.error.fg",
    "description": null,
    "layer": "component"
  },
  {
    "name": "chip.status.warning.bg",
    "type": "color",
    "value": "#FEEAD0",
    "ref": "color.status.warning.bg",
    "description": null,
    "layer": "component"
  },
  {
    "name": "chip.status.warning.fg",
    "type": "color",
    "value": "#472C00",
    "ref": "color.status.warning.fg",
    "description": null,
    "layer": "component"
  },
  {
    "name": "chip.status.info.bg",
    "type": "color",
    "value": "#D5E7FE",
    "ref": "color.status.info.bg",
    "description": null,
    "layer": "component"
  },
  {
    "name": "chip.status.info.fg",
    "type": "color",
    "value": "#03376E",
    "ref": "color.status.info.fg",
    "description": null,
    "layer": "component"
  },
  {
    "name": "chip.highlight.bg",
    "type": "color",
    "value": "#D9F23F",
    "ref": "color.highlight.accent",
    "description": "The 10% chip: milestone moments only.",
    "layer": "component"
  },
  {
    "name": "chip.highlight.fg",
    "type": "color",
    "value": "#141411",
    "ref": "color.highlight.on-accent",
    "description": "Content of the 10% chip.",
    "layer": "component"
  },
  {
    "name": "chip.choice.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Choice chip at rest.",
    "layer": "component"
  },
  {
    "name": "chip.choice.fg",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Choice chip text.",
    "layer": "component"
  },
  {
    "name": "chip.choice.border",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#E3E1DB",
      "style": "solid"
    },
    "ref": "border.default",
    "description": "Border at rest.",
    "layer": "component"
  },
  {
    "name": "chip.choice.height",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Height: the touch target.",
    "layer": "component"
  },
  {
    "name": "chip.choice.font",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 14,
      "lineHeight": 20,
      "letterSpacing": 0
    },
    "ref": "font.role.label",
    "description": "Choice chip text.",
    "layer": "component"
  },
  {
    "name": "chip.choice.selected.bg",
    "type": "color",
    "value": "#141411",
    "ref": "color.surface.inverse",
    "description": "Selected: the same dark pill as the tab bar.",
    "layer": "component"
  },
  {
    "name": "chip.choice.selected.fg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.text.on-inverse",
    "description": "Selected text.",
    "layer": "component"
  },
  {
    "name": "chip.choice.selected.icon",
    "type": "color",
    "value": "#D9F23F",
    "ref": "color.highlight.accent",
    "description": "Selected icon (fixed 10% accent).",
    "layer": "component"
  },
  {
    "name": "input.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Field background.",
    "layer": "component"
  },
  {
    "name": "input.border.focus",
    "type": "border",
    "value": {
      "width": 2,
      "color": "#5347D3",
      "style": "solid"
    },
    "ref": "border.focus.ring",
    "description": "Field focus ring.",
    "layer": "component"
  },
  {
    "name": "input.border",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#6D6C67",
      "style": "solid"
    },
    "ref": "border.input",
    "description": "Field boundary (3:1).",
    "layer": "component"
  },
  {
    "name": "input.fg",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Typed text.",
    "layer": "component"
  },
  {
    "name": "input.placeholder",
    "type": "color",
    "value": "#6D6C67",
    "ref": "color.text.tertiary",
    "description": "Example text.",
    "layer": "component"
  },
  {
    "name": "input.radius",
    "type": "dimension",
    "value": 16,
    "ref": "radius.input",
    "description": "Field radius.",
    "layer": "component"
  },
  {
    "name": "input.height",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Minimum height.",
    "layer": "component"
  },
  {
    "name": "input.font",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_400Regular",
      "fontSize": 16,
      "lineHeight": 24,
      "letterSpacing": 0
    },
    "ref": "font.role.body",
    "description": "Field text.",
    "layer": "component"
  },
  {
    "name": "input.error.border",
    "type": "color",
    "value": "#B81814",
    "ref": "color.status.error.border",
    "description": "Border with an error.",
    "layer": "component"
  },
  {
    "name": "input.large.font",
    "type": "typography",
    "value": {
      "fontFamily": "BricolageGrotesque_700Bold",
      "fontSize": 28,
      "lineHeight": 32,
      "letterSpacing": -0.28
    },
    "ref": "font.role.headline",
    "description": "Hero field of a step (\"What are you saving for?\").",
    "layer": "component"
  },
  {
    "name": "card.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Neutral card. The vertical card uses color.vertical.accent / on-accent from context.",
    "layer": "component"
  },
  {
    "name": "card.border",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#E3E1DB",
      "style": "solid"
    },
    "ref": "border.default",
    "description": "Flat cards: border, no shadow.",
    "layer": "component"
  },
  {
    "name": "card.radius",
    "type": "dimension",
    "value": 20,
    "ref": "radius.card",
    "description": "Card radius.",
    "layer": "component"
  },
  {
    "name": "card.inset",
    "type": "dimension",
    "value": 20,
    "ref": "space.inset.card",
    "description": "Card padding.",
    "layer": "component"
  },
  {
    "name": "list.divider",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#E3E1DB",
      "style": "solid"
    },
    "ref": "border.default",
    "description": "Divider between rows.",
    "layer": "component"
  },
  {
    "name": "list.row.height",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Minimum row height.",
    "layer": "component"
  },
  {
    "name": "list.row.inset",
    "type": "dimension",
    "value": 12,
    "ref": "space.sm",
    "description": "Row vertical padding.",
    "layer": "component"
  },
  {
    "name": "list.row.title",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Row title.",
    "layer": "component"
  },
  {
    "name": "list.row.detail",
    "type": "color",
    "value": "#4E4D48",
    "ref": "color.text.secondary",
    "description": "Row detail.",
    "layer": "component"
  },
  {
    "name": "list.row.positive",
    "type": "color",
    "value": "#014422",
    "ref": "color.status.success.fg",
    "description": "Incoming amount.",
    "layer": "component"
  },
  {
    "name": "badge.bg",
    "type": "color",
    "value": "#F2F0EA",
    "ref": "color.surface.page",
    "description": "Neutral icon badge. With a vertical: color.vertical.accent.",
    "layer": "component"
  },
  {
    "name": "badge.icon",
    "type": "dimension",
    "value": 24,
    "ref": "icon.size.md",
    "description": "Badge icon.",
    "layer": "component"
  },
  {
    "name": "badge.inset",
    "type": "dimension",
    "value": 8,
    "ref": "space.xs",
    "description": "Space around the icon (24 + 2 × 8 = 40).",
    "layer": "component"
  },
  {
    "name": "avatar.bg",
    "type": "color",
    "value": "#141411",
    "ref": "color.surface.inverse",
    "description": "Initials avatar background.",
    "layer": "component"
  },
  {
    "name": "avatar.fg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.text.on-inverse",
    "description": "Initials.",
    "layer": "component"
  },
  {
    "name": "avatar.size",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Diameter.",
    "layer": "component"
  },
  {
    "name": "balance.fg",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Balance figure.",
    "layer": "component"
  },
  {
    "name": "balance.font",
    "type": "typography",
    "value": {
      "fontFamily": "BricolageGrotesque_700Bold",
      "fontSize": 52,
      "lineHeight": 56,
      "letterSpacing": -1.04
    },
    "ref": "font.role.balance",
    "description": "Balance role: one per screen.",
    "layer": "component"
  },
  {
    "name": "balance.cents",
    "type": "dimension",
    "value": 28,
    "ref": "font.size.xl",
    "description": "Size of the cents.",
    "layer": "component"
  },
  {
    "name": "keypad.key.height",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Minimum touch target of each key (plus space.md of air).",
    "layer": "component"
  },
  {
    "name": "keypad.key.font",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 20,
      "lineHeight": 28,
      "letterSpacing": 0
    },
    "ref": "font.role.title",
    "description": "Digits.",
    "layer": "component"
  },
  {
    "name": "keypad.key.fg",
    "type": "color",
    "value": "#141411",
    "ref": "color.text.primary",
    "description": "Digits and the delete icon.",
    "layer": "component"
  },
  {
    "name": "slider.track",
    "type": "color",
    "value": "#E3E1DB",
    "ref": "color.border.default",
    "description": "Track.",
    "layer": "component"
  },
  {
    "name": "slider.fill",
    "type": "color",
    "value": "#141411",
    "ref": "color.surface.inverse",
    "description": "Filled part of the track.",
    "layer": "component"
  },
  {
    "name": "slider.height",
    "type": "dimension",
    "value": 8,
    "ref": "space.xs",
    "description": "Track thickness.",
    "layer": "component"
  },
  {
    "name": "slider.thumb.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Thumb.",
    "layer": "component"
  },
  {
    "name": "slider.thumb.border",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#6D6C67",
      "style": "solid"
    },
    "ref": "border.input",
    "description": "Thumb outline (3:1).",
    "layer": "component"
  },
  {
    "name": "slider.thumb.size",
    "type": "dimension",
    "value": 32,
    "ref": "space.2xl",
    "description": "Thumb diameter.",
    "layer": "component"
  },
  {
    "name": "slider.thumb.elevation",
    "type": "shadow",
    "value": "0px 6px 20px 0px #1414111F",
    "ref": "elevation.floating",
    "description": "The thumb floats above the track.",
    "layer": "component"
  },
  {
    "name": "segmented.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Control background.",
    "layer": "component"
  },
  {
    "name": "segmented.border",
    "type": "border",
    "value": {
      "width": 1,
      "color": "#E3E1DB",
      "style": "solid"
    },
    "ref": "border.default",
    "description": "Control border.",
    "layer": "component"
  },
  {
    "name": "segmented.indicator",
    "type": "color",
    "value": "#141411",
    "ref": "color.surface.inverse",
    "description": "Pill of the active option.",
    "layer": "component"
  },
  {
    "name": "segmented.label",
    "type": "color",
    "value": "#4E4D48",
    "ref": "color.text.secondary",
    "description": "Option at rest.",
    "layer": "component"
  },
  {
    "name": "segmented.inset",
    "type": "dimension",
    "value": 4,
    "ref": "space.2xs",
    "description": "Space between the border and the pill.",
    "layer": "component"
  },
  {
    "name": "segmented.active.label",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.text.on-inverse",
    "description": "Active option.",
    "layer": "component"
  },
  {
    "name": "slide-confirm.bg",
    "type": "color",
    "value": "#5347D3",
    "ref": "color.brand.primary",
    "description": "Track: this is the primary action.",
    "layer": "component"
  },
  {
    "name": "slide-confirm.fill",
    "type": "color",
    "value": "#4034AC",
    "ref": "color.brand.primary.pressed",
    "description": "Dragged part of the track.",
    "layer": "component"
  },
  {
    "name": "slide-confirm.fg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.brand.on-primary",
    "description": "Label.",
    "layer": "component"
  },
  {
    "name": "slide-confirm.font",
    "type": "typography",
    "value": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 14,
      "lineHeight": 20,
      "letterSpacing": 0
    },
    "ref": "font.role.label",
    "description": "Label.",
    "layer": "component"
  },
  {
    "name": "slide-confirm.inset",
    "type": "dimension",
    "value": 4,
    "ref": "space.2xs",
    "description": "Space around the thumb.",
    "layer": "component"
  },
  {
    "name": "slide-confirm.thumb.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.brand.on-primary",
    "description": "Thumb.",
    "layer": "component"
  },
  {
    "name": "slide-confirm.thumb.icon",
    "type": "color",
    "value": "#5347D3",
    "ref": "color.brand.primary",
    "description": "Thumb arrow.",
    "layer": "component"
  },
  {
    "name": "slide-confirm.thumb.size",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Thumb diameter: the touch target.",
    "layer": "component"
  },
  {
    "name": "progress.height",
    "type": "dimension",
    "value": 8,
    "ref": "space.xs",
    "description": "Progress bar.",
    "layer": "component"
  },
  {
    "name": "progress.slim",
    "type": "dimension",
    "value": 4,
    "ref": "space.2xs",
    "description": "Slim bar (lists, flow steps).",
    "layer": "component"
  },
  {
    "name": "progress.ring.stroke",
    "type": "dimension",
    "value": 12,
    "ref": "space.sm",
    "description": "Ring thickness.",
    "layer": "component"
  },
  {
    "name": "progress.step.track",
    "type": "color",
    "value": "#E3E1DB",
    "ref": "color.border.default",
    "description": "Pending step.",
    "layer": "component"
  },
  {
    "name": "progress.step.done",
    "type": "color",
    "value": "#141411",
    "ref": "color.surface.inverse",
    "description": "Completed step.",
    "layer": "component"
  },
  {
    "name": "switch.on",
    "type": "color",
    "value": "#5347D3",
    "ref": "color.brand.primary",
    "description": "Track when on.",
    "layer": "component"
  },
  {
    "name": "switch.off",
    "type": "color",
    "value": "#6D6C67",
    "ref": "color.border.input",
    "description": "Track when off (3:1); outline and handle of the Android switch.",
    "layer": "component"
  },
  {
    "name": "switch.thumb",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Thumb on both platforms (iOS UISwitch and Material 3 switch when on).",
    "layer": "component"
  },
  {
    "name": "tabbar.bg",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.surface.card",
    "description": "Tab bar pill.",
    "layer": "component"
  },
  {
    "name": "tabbar.strip",
    "type": "color",
    "value": "#F2F0EA",
    "ref": "color.surface.page",
    "description": "Opaque strip: nothing shows underneath.",
    "layer": "component"
  },
  {
    "name": "tabbar.radius",
    "type": "dimension",
    "value": 999,
    "ref": "radius.pill",
    "description": "Pill-shaped bar.",
    "layer": "component"
  },
  {
    "name": "tabbar.elevation",
    "type": "shadow",
    "value": "0px 6px 20px 0px #1414111F",
    "ref": "elevation.floating",
    "description": "The bar floats.",
    "layer": "component"
  },
  {
    "name": "tabbar.inset",
    "type": "dimension",
    "value": 4,
    "ref": "space.2xs",
    "description": "Space between the bar and the active pill.",
    "layer": "component"
  },
  {
    "name": "tabbar.item.icon",
    "type": "color",
    "value": "#6D6C67",
    "ref": "color.text.tertiary",
    "description": "Icon at rest (outline).",
    "layer": "component"
  },
  {
    "name": "tabbar.item.height",
    "type": "dimension",
    "value": 48,
    "ref": "size.touch.min",
    "description": "Item height.",
    "layer": "component"
  },
  {
    "name": "tabbar.item.active.bg",
    "type": "color",
    "value": "#141411",
    "ref": "color.surface.inverse",
    "description": "Active pill.",
    "layer": "component"
  },
  {
    "name": "tabbar.item.active.icon",
    "type": "color",
    "value": "#D9F23F",
    "ref": "color.highlight.accent",
    "description": "Active icon (filled, lime).",
    "layer": "component"
  },
  {
    "name": "tabbar.item.active.label",
    "type": "color",
    "value": "#F8F7F1",
    "ref": "color.text.on-inverse",
    "description": "Active label.",
    "layer": "component"
  },
  {
    "name": "confetti.duration",
    "type": "duration",
    "value": 1800,
    "ref": "motion.duration.effect",
    "description": "Lifetime of the burst, from launch to the last piece leaving the screen.",
    "layer": "component"
  },
  {
    "name": "confetti.gravity",
    "type": "number",
    "value": 1400,
    "ref": null,
    "description": "Downward acceleration of each piece, in pt/s² (dp/s² on Android).",
    "layer": "component"
  },
  {
    "name": "confetti.count",
    "type": "number",
    "value": 48,
    "ref": null,
    "description": "Pieces per burst.",
    "layer": "component"
  }
];
