// Builds src/theme/tokens.ts from the DTCG sources in tokens/ (FOUNDATIONS.md §11).
// Output is a flat map keyed by the exact token name from TOKEN-NAMING.md,
// e.g. tokens['color.brand.primary.pressed'], with values ready for React Native.
import StyleDictionary from 'style-dictionary';

const ROOT = '__root';

// DTCG `$root` lets a group also be a token (color.brand.primary + .pressed).
// Style Dictionary doesn't read `$root`, so move it to a child we strip later.
StyleDictionary.registerPreprocessor({
  name: 'vuno/dtcg-root',
  preprocessor: (tree) => {
    const walk = (node) => {
      if (!node || typeof node !== 'object' || '$value' in node) return;
      if ('$root' in node) {
        node[ROOT] = node.$root;
        delete node.$root;
      }
      Object.keys(node).forEach((key) => !key.startsWith('$') && walk(node[key]));
    };
    walk(tree);
    // References to a $root group ({color.brand.primary}) now point at its __root child.
    const roots = new Set();
    const find = (node, path) => {
      if (!node || typeof node !== 'object' || '$value' in node) return;
      if (ROOT in node) roots.add(path.join('.'));
      Object.keys(node).forEach((key) => !key.startsWith('$') && find(node[key], [...path, key]));
    };
    find(tree, []);
    const fix = (v) =>
      typeof v === 'string'
        ? v.replace(/\{([^}]+)\}/g, (m, ref) => (roots.has(ref) ? `{${ref}.${ROOT}}` : m))
        : Array.isArray(v)
          ? v.map(fix)
          : v && typeof v === 'object'
          ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, fix(x)]))
          : v;
    const rewrite = (node) => {
      if (!node || typeof node !== 'object') return;
      if ('$value' in node) {
        node.$value = fix(node.$value);
        return;
      }
      Object.keys(node).forEach((key) => !key.startsWith('$') && rewrite(node[key]));
    };
    rewrite(tree);
    return tree;
  },
});

// A component token like button.primary.font aliases a role: it inherits that role's RN font instance.
let byName = new Map();
const rnFamilyOf = (token) => {
  const ref = token.original?.$value;
  if (typeof ref !== 'string' || !/^\{[^}]+\}$/.test(ref)) return undefined;
  return byName.get(ref.slice(1, -1))?.$extensions?.['com.vuno.react-native']?.fontFamily;
};

const px = (v) => (typeof v === 'string' && v.endsWith('px') ? Number(v.slice(0, -2)) : v);
const ms = (v) => (typeof v === 'string' && v.endsWith('ms') ? Number(v.slice(0, -2)) : v);

// Converts a resolved DTCG value to what React Native expects.
function toNative(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'dimension':
      return px(v);
    case 'duration':
      return ms(v);
    case 'shadow': {
      const layers = Array.isArray(v) ? v : [v];
      // RN boxShadow string (new architecture), same fields as Figma's drop shadow.
      return layers.map((l) => `${px(l.offsetX)}px ${px(l.offsetY)}px ${px(l.blur)}px ${px(l.spread)}px ${l.color}`).join(', ');
    }
    case 'border':
      return { width: px(v.width), color: v.color, style: v.style };
    case 'typography': {
      const rnFamily = token.$extensions?.['com.vuno.react-native']?.fontFamily ?? rnFamilyOf(token);
      // Custom fonts: each weight is its own family, so fontWeight is omitted.
      return { fontFamily: rnFamily ?? v.fontFamily, fontSize: px(v.fontSize), lineHeight: px(v.lineHeight), letterSpacing: px(v.letterSpacing) };
    }
    default:
      return v;
  }
}

StyleDictionary.registerFormat({
  name: 'vuno/react-native-ts',
  format: ({ dictionary }) => {
    byName = new Map(dictionary.allTokens.map((t) => [t.path.filter((p) => p !== ROOT).join('.'), t]));
    const entries = dictionary.allTokens.map((token) => {
      const name = token.path.filter((p) => p !== ROOT).join('.');
      return [name, toNative(token)];
    });
    const body = entries.map(([name, value]) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)},`).join('\n');
    return [
      '// Generated by scripts/build-tokens.mjs from tokens/*.json. Do not edit by hand.',
      '',
      'export const tokens = {',
      body,
      '} as const;',
      '',
      'export type TokenName = keyof typeof tokens;',
      '',
    ].join('\n');
  },
});

// Metadata for the documentation (Storybook): name, type, value, alias and usage.
StyleDictionary.registerFormat({
  name: 'vuno/token-meta-ts',
  format: ({ dictionary }) => {
    byName = new Map(dictionary.allTokens.map((t) => [t.path.filter((p) => p !== ROOT).join('.'), t]));
    const strip = (ref) => ref.replace(/^\{|\}$/g, '').split('.').filter((p) => p !== ROOT).join('.');
    const meta = dictionary.allTokens.map((token) => {
      const original = token.original.$value;
      return {
        name: token.path.filter((p) => p !== ROOT).join('.'),
        type: token.$type,
        value: toNative(token),
        ref: typeof original === 'string' && /^\{[^}]+\}$/.test(original) ? strip(original) : null,
        description: token.$description ?? null,
        layer: token.filePath.includes('primitives') ? 'primitive' : token.filePath.includes('component') ? 'component' : 'semantic',
      };
    });
    return [
      '// Generated by scripts/build-tokens.mjs from tokens/*.json. Do not edit by hand.',
      '',
      'export type TokenMeta = {',
      '  name: string;',
      '  type: string;',
      '  value: unknown;',
      '  ref: string | null;',
      '  description: string | null;',
      "  layer: 'primitive' | 'semantic' | 'component';",
      '};',
      '',
      `export const tokenMeta: TokenMeta[] = ${JSON.stringify(meta, null, 2)};`,
      '',
    ].join('\n');
  },
});

const sd = new StyleDictionary({
  source: ['tokens/primitives.json', 'tokens/semantic.light.json', 'tokens/component.json'],
  preprocessors: ['vuno/dtcg-root'],
  log: { verbosity: 'default' },
  platforms: {
    reactNative: {
      transforms: ['name/kebab'],
      buildPath: 'src/theme/',
      files: [
        { destination: 'tokens.ts', format: 'vuno/react-native-ts' },
        { destination: 'tokens.meta.ts', format: 'vuno/token-meta-ts' },
      ],
    },
  },
});

await sd.buildAllPlatforms();
